"""Markdown formatter for VideoUnit reports."""

from datetime import datetime
from typing import Any


def format_markdown(result: dict, contract: dict) -> str:
    """
    Format run result as Markdown report.

    Args:
        result: Test result dict from run.json
        contract: The contract/duties YAML as dict

    Returns:
        Markdown formatted report string
    """
    lines = []

    # Header
    run_id = result.get("run_id", "unknown")
    timestamp = _format_timestamp(result.get("timestamp"))
    overall = result.get("overall", 0)
    scores = result.get("scores", {})

    lines.append(f"# VideoUnit Report - {run_id}")
    lines.append("")
    lines.append(f"**Generated:** {timestamp}")
    lines.append("")

    # Score Summary
    status_icon = "PASS" if overall >= 80 else "WARN" if overall >= 60 else "FAIL"
    lines.append(f"## Overall Score: {overall}% `[{status_icon}]`")
    lines.append("")

    # Score Cards Table
    if scores:
        lines.append("### Score Breakdown")
        lines.append("")
        lines.append("| Category | Score | Status |")
        lines.append("|----------|-------|--------|")

        categories = [
            ("accuracy", "Accuracy"),
            ("completeness", "Completeness"),
            ("coherence", "Coherence"),
            ("quality", "Quality"),
            ("timing", "Timing"),
        ]

        for key, label in categories:
            value = scores.get(key, 0)
            status = "PASS" if value >= 80 else "WARN" if value >= 60 else "FAIL"
            lines.append(f"| {label} | {value}/100 | {status} |")

        lines.append("")

    # Failure Summary
    failures = result.get("failures", [])
    num_failures = result.get("num_failures", len(failures))
    pass_count = result.get("passed_count", 0)

    lines.append(f"## Test Results: {pass_count} passed, {num_failures} failed")
    lines.append("")

    # Failure List
    if failures:
        lines.append("### Failures")
        lines.append("")

        for i, failure in enumerate(failures, 1):
            frame = failure.get("frame_number", "N/A")
            ts = failure.get("timestamp", "N/A")
            severity = failure.get("severity", "fail")
            ftype = failure.get("type", "assertion")
            message = failure.get("message", "No message")

            lines.append(f"#### {i}. [{severity.upper()}] {ftype.title()}")
            lines.append("")
            lines.append(f"- **Frame:** {frame}")
            lines.append(f"- **Timestamp:** {ts}")
            lines.append(f"- **Message:** {message}")
            lines.append("")

    # Evidence References
    evidence_frames = result.get("evidence_frames", [])
    if evidence_frames:
        lines.append("### Evidence Gallery")
        lines.append("")
        for frame in evidence_frames:
            path = frame.get("path", "")
            frame_num = frame.get("frame_number", "N/A")
            lines.append(f"- Frame {frame_num}: `{path}`")
        lines.append("")

    # Contract Info
    contract_name = contract.get("test", {}).get("name", "Unknown")
    assertions = contract.get("assertions", [])
    lines.append(f"## Contract: {contract_name}")
    lines.append("")
    lines.append(f"Total assertions: {len(assertions)}")
    lines.append("")

    # Assertions List
    if assertions:
        lines.append("### Assertions")
        lines.append("")
        for i, assertion in enumerate(assertions, 1):
            assertion_type = assertion.get("type", "check")
            description = assertion.get("description", assertion.get("check", ""))
            lines.append(f"{i}. **{assertion_type}**: {description}")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Generated by VideoUnit*")

    return "\n".join(lines)


def _format_timestamp(timestamp: Any) -> str:
    """Format timestamp for display."""
    if not timestamp:
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")

    if isinstance(timestamp, str):
        try:
            dt = datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
            return dt.strftime("%Y-%m-%d %H:%M:%S UTC")
        except (ValueError, AttributeError):
            return str(timestamp)

    return str(timestamp)
